#
# https://github.com/aterenin/minima-reboot/
# remote_theme: aterenin/minima-reboot
#
# https://github.com/alexander-heimbuch/millidocs
# remote_theme: alexander-heimbuch/millidocs
#

remote_theme: alexander-heimbuch/millidocs
title: PoufDB
name: name
description: 
markdown: kramdown
#markdown: redcarpet
baseurl:
github:
  repository_url: https://github.com/ablaternae/py-pouffe/

