#
# https://github.com/aterenin/minima-reboot/
# remote_theme: aterenin/minima-reboot
# https://github.com/olivier3lanc/Jekyll-LibDoc
# remote_theme: olivier3lanc/Jekyll-LibDoc
# https://github.com/xriley/PrettyDocs-Theme
# remote_theme: leakyabstractions/pretty-docs
#


remote_theme: olivier3lanc/Jekyll-LibDoc
title: PoufDB
name: name
description: 
#keep_files: [cache]
#markdown: kramdown
markdown: redcarpet
baseurl:
github:
  repository_url: https://github.com/ablaternae/py-pouffe/
collections:
  guides:
    output: true
